# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Francesco Gallo
tagline: Ingegnere Civile - Matematico
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'xxxxxx xxxxxx xxxxxx xxxxxx xxxxxx xxxxxx xxxxxx xxxxxx xxxxxx xxxxxx xxxxxx xxxxxx xxxxxx '

#sidebar links
email: galfra@libero.it
website: ingfrancescogallo.com #do not add http://
#linkedin: alandoe
#github: sharu725
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: 

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
